import { trainingName } from './trainingSimulation';
import { reportMetrics, type ActivityReport } from './performance';
import { lazy, Suspense, useEffect, useRef, useState } from 'react';
import { useGameStore } from '../../stores/gameStore';
import { activityRestriction } from '../../utils/dogDevelopment';
import { calculateFoodConsumption } from '../../utils/careCalculations';
import { DISCIPLINES, DISCIPLINE_INFO, clubQualified, challengeQualified, discoveredText, fieldAbility, keeperBonus, learned, newClubProgress, recordFor, roundScore, sampledAll, standings, type ClubEvent, type Discipline } from './model';
import { completeClubRound, enrollClub, firstUntried, leaveClubRun, startClubRun } from './progress';
import './club.css';
const TrainingGame = lazy(() => import('./TrainingGame'));
const SearchAdventure = lazy(() => import('./SearchAdventure'));
const FieldGame = lazy(() => import('./FieldGame'));
const AgilityGame = lazy(() => import('../agility/AgilityGame'));
type Navigate = (view: string, options?: { shopTab?: 'items' | 'pound' }) => void;

export function ClubInvitation({ onNavigate }: { onNavigate: Navigate }) {
  const { dogs, selectedDog, tutorialProgress } = useGameStore();
  const dog = dogs.find(d => d.id === selectedDog?.id && !d.is_dead) ?? dogs.find(d => !d.is_dead), progress = tutorialProgress.fieldClub;
  const tried = dog ? DISCIPLINES.filter(d => (recordFor(progress, dog.id, d).clubSessions ?? recordFor(progress, dog.id, d).sessions) > 0).length : 0;
  return <section className="club-invitation" aria-label="Your Field Club journey"><div><small>{progress?.completedAt ? 'YOUR KENNEL, YOUR TEAM' : 'YOUR FIRST GOAL'}</small><h2>{progress?.completedAt ? 'Build on your first club trial.' : `Discover what ${dog?.name ?? 'your dog'} can do.`}</h2><p>{progress?.active ? 'Your visit is saved. Return to the club to continue the next round.' : progress?.completedAt ? 'Train a weakness, enter a specialist event, or give a second rescue a role on your team.' : `Choose an event your dog qualifies for. Train skills to unlock more, then build toward a combined trial. ${tried}/4 disciplines explored.`}</p></div><button className="journey-primary" onClick={() => { enrollClub(); onNavigate('fieldClub'); }}>{progress?.active ? 'Continue club visit' : 'Visit the Field Club'} <span aria-hidden="true">→</span></button></section>;
}
export default function FieldClub({ onNavigate }: { onNavigate: Navigate }) {
  const state = useGameStore(), { user, dogs, selectedDog, tutorialProgress } = state;
  const [message, setMessage] = useState(''), [playing, setPlaying] = useState(false), [roster, setRoster] = useState<Partial<Record<Discipline, string>>>({});
  const [leaving, setLeaving] = useState(false), reportRef = useRef<HTMLElement>(null);
  useEffect(() => { enrollClub(); }, []);
  const progress = tutorialProgress.fieldClub ?? newClubProgress(), run = progress.active;
  const dog = dogs.find(d => d.id === selectedDog?.id && !d.is_dead) ?? dogs.find(d => !d.is_dead);
  const runId = run?.id, roundIndex = run?.results.length;
  useEffect(() => { if (runId) reportRef.current?.scrollIntoView({ block: 'start', behavior: 'smooth' }); }, [runId, roundIndex]);
  if (!user || !dog) return <section className="field-club"><h1>Your next partnership</h1><p>Choose a living companion to visit the club.</p><button className="journey-primary" onClick={() => onNavigate('kennel')}>Visit your dogs</button></section>;
  const record = (d: Discipline) => recordFor(progress, dog.id, d), tried = DISCIPLINES.filter(d => (record(d).clubSessions ?? record(d).sessions) > 0).length;
  const next = firstUntried(progress, dog.id), reason = activityRestriction(dog), latest = progress.matches[0];
  const begin = (kind: ClubEvent, discipline?: Discipline, challenge = false) => {
    const rounds = discipline ? [{ discipline, dogId: dog.id }] : DISCIPLINES.map(d => ({ discipline: d, dogId: kind === 'team' ? roster[d] ?? dog.id : dog.id }));
    const result = startClubRun(kind, rounds, kind === 'practice' ? 'training' : 'club', challenge); setMessage(result.message);
    if (result.success) { setPlaying(false); reportRef.current?.scrollIntoView({ block: 'start' }); }
  };
  const care = (action: () => { success: boolean; message?: string }) => setMessage(action().message ?? 'Care complete.');
  const liveRound = run?.rounds[run.results.length], roundDog = dogs.find(d => d.id === liveRound?.dogId);
  const finish = (score: number, report?: ActivityReport) => {
    if (!run) return;
    const result = completeClubRound(run.id, run.results.length, score, report);
    setMessage(result.message); setPlaying(false);
    requestAnimationFrame(() => reportRef.current?.scrollIntoView({ block: 'start', behavior: 'smooth' }));
  };
  const trialReady = sampledAll(progress, dog.id);
  return <div className="field-club">
    <header className="club-grounds-hero"><div><small>THE FIELD CLUB / FOUNDERS' PREVIEW</small><h1>Four strengths.<br/><em>One partnership.</em></h1><p>Discover your dog's talents. Develop their weaker skills. Build a kennel that can compete together.</p><span>Agility · Scent search · Herding · Water retrieval</span></div><div className="club-passport"><small>{progress.completedAt ? 'CLUB MEMBER' : 'YOUR INTRODUCTION'}</small><strong>{tried}<span>/4</span></strong><p>disciplines explored with {dog.name}</p><div>{DISCIPLINES.map(d => <span key={d} className={(record(d).clubSessions ?? record(d).sessions) ? 'is-earned' : ''} title={DISCIPLINE_INFO[d].name}>{DISCIPLINE_INFO[d].name}</span>)}</div></div></header>
    <section className="club-next-step" aria-label="Your next step"><div><small>{run ? 'VISIT IN PROGRESS' : progress.completedAt ? 'MAKE YOUR NEXT DECISION' : 'START HERE'}</small><h2>{run ? 'Pick up where you left off.' : next ? `Try ${DISCIPLINE_INFO[next].name.toLowerCase()} with ${dog.name}.` : !progress.completedAt ? 'Put all four skills to the test.' : 'A stronger dog, or a stronger team?'}</h2><p>{run ? 'Completed rounds are saved. You can care for your dogs between rounds and resume after a reload.' : next ? 'Choose any event your dog qualifies for. Separate yard exercises develop focus, control, footwork and conditioning for locked events.' : !progress.completedAt ? 'Enter the four-round combined trial. Completing every task earns a $150 first-completion grant.' : 'Specialist events reward strengths. Combined trials expose weaknesses. Team events let different dogs contribute.'}</p></div>{!run && <button className="journey-primary" onClick={() => next ? begin(clubQualified(dog, next, record(next)) ? 'specialist' : 'practice', next) : begin('combined')}>{next ? `${clubQualified(dog, next, record(next)) ? 'Play' : 'Train for'} ${DISCIPLINE_INFO[next].name}` : 'Enter combined trial'}</button>}</section>
    <div className="club-preparation"><label>Your companion<select aria-label="Field Club companion" value={dog.id} onChange={e => state.selectDog(dogs.find(d => d.id === e.target.value)!)}>{dogs.filter(d => !d.is_dead).map(d => <option key={d.id} value={d.id}>{d.name}</option>)}</select></label><div><strong>Keeper level {user.level}</strong><span>+{Math.round((keeperBonus(user) - 1) * 100)}% club learning · each level adds 4%</span></div><div><strong>{dog.energy_stat}% energy · {dog.training_points} TP</strong><span>Saved training and event rounds use 6 energy and 4 TP</span></div></div>
    {message && <p className="club-notice" role="status">{message}</p>}
    <details className="club-care" open={!!reason}><summary>Prepare your companion · Food {Math.round(dog.hunger)}% · Water {Math.round(dog.thirst)}% · Pantry {user.food_storage.toFixed(1)}</summary><p>{reason ?? 'Training is open when your dog is fit. Events need at least 60% food and water, and enough energy for every assigned round.'}</p><div><button onClick={() => care(() => state.purchaseItem(null, { food_storage: 10 }, 40, 0))}>Buy 10 food · $40</button><button disabled={dog.hunger >= 95 || user.food_storage < calculateFoodConsumption(dog.size)} onClick={() => care(() => state.feedDog(dog.id))}>Serve meal · {calculateFoodConsumption(dog.size)} food</button><button disabled={dog.thirst >= 95} onClick={() => care(() => state.waterDog(dog.id))}>Fresh water · free</button><button disabled={dog.energy_stat >= 95} onClick={() => care(() => state.restDog(dog.id))}>Rest together · free</button>{reason && <button onClick={() => onNavigate('vet')}>Visit the care room</button>}</div><p>Buy food before serving a meal. Rest restores energy; training points recover on the daily schedule. Care and supplies use your existing kennel inventory.</p></details>
    {run && <section className="club-round-board" ref={reportRef} aria-label="Current club visit"><small>{run.exercise === 'training' ? 'TRAINING VISIT' : run.kind === 'practice' ? 'PRACTICE VISIT' : run.kind === 'team' ? 'KENNEL TEAM TRIAL' : run.kind === 'specialist' ? 'SPECIALIST EVENT' : 'COMBINED TRIAL'}</small><h2>Round {run.results.length + 1} of {run.rounds.length}: {liveRound && DISCIPLINE_INFO[liveRound.discipline].name}</h2><p>{roundDog?.name ?? 'This dog is no longer available'} is up next. Completed rounds keep their score when you leave and return.</p><ol>{run.rounds.map((r, i) => <li key={r.discipline}><span>{i + 1}. {DISCIPLINE_INFO[r.discipline].name}</span><strong>{run.results[i] ? `${run.results[i].score}/100 · ${run.results[i].dogName}` : dogs.find(d => d.id === r.dogId)?.name ?? 'Unavailable dog'}</strong></li>)}</ol><div className="club-actions"><button className="journey-primary" disabled={!roundDog} onClick={() => { if (roundDog && activityRestriction(roundDog)) { setMessage(activityRestriction(roundDog)!); return; } setPlaying(true); }}>Begin {liveRound && DISCIPLINE_INFO[liveRound.discipline].name} round</button><button onClick={() => setLeaving(true)}>Leave this visit</button></div>{leaving && <div className="club-leave"><p>Completed rounds keep their training gains. Leaving ends this event without its completion grant.</p><button onClick={() => { leaveClubRun(); setLeaving(false); setPlaying(false); }}>End visit and return to club</button><button onClick={() => setLeaving(false)}>Keep my visit</button></div>}</section>}
    {!run && latest && <section className="club-results" ref={reportRef} aria-label="Latest club result"><div><small>{latest.kind === 'practice' ? 'TRAINING SAVED' : 'YOUR LAST EVENT'}</small><h2>{latest.kind === 'practice' ? `${latest.results[0].dogName}: ${latest.average}/100` : `${latest.average}/100 overall · placed ${latest.placement} of 4`}</h2><p>{latest.cash > 0 ? `$${latest.cash} first-completion grant added to your kennel.` : 'Your development and results are saved. Complete every task in an event to earn its first-completion grant.'}</p></div><div className="club-result-rounds">{latest.results.map(r => <div key={r.discipline}><span>{DISCIPLINE_INFO[r.discipline].name} · {r.dogName}</span><strong>{r.score}/100</strong>{r.report?.caseName && <small>{r.report.caseName}</small>}<small>+{r.gain} experience · {DISCIPLINE_INFO[r.discipline].effect}</small>{r.abilityBefore !== undefined && r.abilityAfter !== undefined && <small>Working ability: {r.abilityBefore.toFixed(1)} to {r.abilityAfter.toFixed(1)}</small>}{r.report && <details className="activity-evidence"><summary>What affected this result</summary><dl>{reportMetrics(r.report).map(([label,value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p>Completion {r.report.completionPoints}/60 | Pace {r.report.pacePoints}/25 | Control {r.report.controlPoints}/15</p></details>}</div>)}</div>{latest.kind !== 'practice' && <><div className="club-score-table"><table><caption>Local club standings · simulated rivals</caption><thead><tr><th>Kennel / dog</th>{latest.results.map(r => <th key={r.discipline}>{DISCIPLINE_INFO[r.discipline].name}</th>)}<th>Overall</th></tr></thead><tbody>{standings(latest.results, latest.kind === 'team').map(r => <tr key={r.name} className={r.player ? 'is-player' : ''}><th>{r.name}</th>{r.scores.map((v, i) => <td key={i}>{v}</td>)}<td>{r.average}</td></tr>)}</tbody></table></div><p><strong>Your next opportunity:</strong> {latest.results.length === 1 ? 'Train toward an advanced event, or explore another discipline with this dog.' : <>{DISCIPLINE_INFO[[...latest.results].sort((a, b) => a.score - b.score)[0].discipline].name} was your lowest-scoring round. Train its underlying skills to improve your combined result, or assign that round to a stronger teammate.</>}</p></>}</section>}
    <section aria-label="Four disciplines"><div className="club-section-heading"><div><small>LEARN BY DOING</small><h2>Find what comes naturally.</h2></div><p>Rescue potential is discovered through experience.</p></div><div className="club-sports">{DISCIPLINES.map((d, i) => <article key={d} className={`club-sport sport-${d}`} style={{ '--sport-color': DISCIPLINE_INFO[d].color } as React.CSSProperties}><div className="club-sport-art" aria-hidden="true"><span>{String(i + 1).padStart(2, '0')}</span><svg viewBox="0 0 240 90"><path d={d === 'agility' ? 'M25 75V30H90V75M115 75Q155 0 195 75M25 45H90' : d === 'search' ? 'M30 70Q60 15 95 55T175 35M175 20V50M160 35H190' : d === 'herding' ? 'M25 70L95 35L145 60L215 25M170 15H225V70H170' : 'M10 60Q40 35 70 60T130 60T190 60T250 60M140 25V45M130 35H150'}/></svg></div><div className="club-sport-copy"><small>{DISCIPLINE_INFO[d].short}</small><h3>{DISCIPLINE_INFO[d].name}</h3><p>{DISCIPLINE_INFO[d].detail}</p><div className="club-ability"><strong>{discoveredText(dog, d, record(d))}</strong><span>{DISCIPLINE_INFO[d].effect}</span><label>Learned ability <b>{learned(record(d)).toFixed(1)}/100</b></label><progress max={100} value={learned(record(d))}/><small>{record(d).sessions} sessions · {record(d).bestRules === 2 && (d !== 'search' || record(d).bestActivity === 'woodland-search') ? 'best' : 'earlier best'} {record(d).best}/100</small></div><button disabled={!!run || !!reason} onClick={() => begin('practice', d)}>Train: {trainingName(d)}</button><p className="club-qualification">{clubQualified(dog,d,record(d)) ? `Qualified - working ability ${fieldAbility(dog,d,record(d)).toFixed(1)}` : `Training needed: working ability ${fieldAbility(dog,d,record(d)).toFixed(1)} / 35`}</p><button className="club-sport-event" disabled={!!run || !!reason || !clubQualified(dog,d,record(d))} onClick={() => begin('specialist', d)}>Play {DISCIPLINE_INFO[d].name}</button></div></article>)}</div></section>
    <section className="club-event-grid" aria-label="Training goals">{(['search','water'] as const).map(d => <article key={d}><small>ADVANCED EVENT</small><h2>{d === 'search' ? 'Deep woods expedition' : 'Cross-current endurance retrieve'}</h2><p>{d === 'search' ? 'Follow five pieces of evidence through a longer woodland case. Read the trail and recover from animal distractions.' : 'Bring four distant dummies home, including one inside the strong current. Conditioning and efficient returns matter.'}</p><p>Qualification: {Math.min(120,record(d).xp)}/120 experience and {fieldAbility(dog,d,record(d)).toFixed(1)}/55 working ability.</p><button disabled={!!run || !!reason || !challengeQualified(dog,d,record(d))} onClick={() => begin('specialist',d,true)}>{challengeQualified(dog,d,record(d)) ? 'Enter advanced event' : 'Train to qualify'}</button><button disabled={!!run || !!reason} onClick={() => begin('practice',d)}>Train: {trainingName(d)}</button></article>)}</section>
    <section className="club-event-grid" aria-label="Competition pathways"><article><small>ONE DOG / FOUR DISCIPLINES</small><h2>The combined trial</h2><p>One companion completes every round. Equal scoring makes every skill matter. This is a beginner club event, not a national title.</p><p>{trialReady ? 'Your dog has tried all four sports.' : `${tried}/4 club events complete. Complete a club event in each discipline before entering.`}</p><button className="journey-primary" disabled={!!run || !trialReady} onClick={() => begin('combined')}>Enter combined trial</button><small>Free entry · $150 first completion · replay for records and development</small></article><article><small>YOUR KENNEL / COMPLEMENTARY STRENGTHS</small><h2>The team trial</h2><p>Assign a dog to each round. Use at least two dogs; a versatile companion can take more than one round.</p>{progress.completedAt ? <>{DISCIPLINES.map(d => <label className="club-team-slot" key={d}>{DISCIPLINE_INFO[d].name}<select aria-label={`${DISCIPLINE_INFO[d].name} teammate`} value={roster[d] ?? dog.id} onChange={e => setRoster({ ...roster, [d]: e.target.value })} disabled={!!run}>{dogs.filter(v => !v.is_dead).map(v => <option key={v.id} value={v.id}>{v.name} · {recordFor(progress, v.id, d).sessions ? `best ${recordFor(progress, v.id, d).best}` : 'untried'}</option>)}</select></label>)}<button disabled={!!run || dogs.filter(v => !v.is_dead).length < 2} className="journey-primary" onClick={() => begin('team')}>Enter team trial</button><button onClick={() => onNavigate('shop', { shopTab: 'pound' })}>Meet another rescue · adoption $100</button><small>Free entry · $120 first completion · uses dogs from your kennel</small></> : <p className="club-lock-note">Finish your first club event to open team entries and second-dog adoption. Your founding rescue keeps its place in the team.</p>}</article></section>
    <section className="club-horizons"><small>THE KENNEL YOU ARE BUILDING</small><h2>This is where a legacy begins.</h2><div><article><span>PLAYABLE NOW</span><h3>A partner and a team</h3><p>Four sports, individual records, specialist events, combined trials, team selection, and a growing keeper skill.</p></article><article><span>EXISTING SYSTEM / LATER IN YOUR JOURNEY</span><h3>The next generation</h3><p>Develop parents, plan a pairing, and raise distinct puppies. Breeding requires suitable adults and kennel level 3 with nursery space; national titles are not required.</p>{progress.completedAt ? <button onClick={() => onNavigate('breeding')}>Explore breeding readiness</button> : <p>Finish your first club event to open breeding planning.</p>}</article><article><span>PLANNED EXPANSIONS</span><h3>A wider world</h3><p>Regional and national multi-event championships, working assignments, disc, flyball, tracking, show routines, and additional facilities. These are future content, not currently playable events.</p></article></div><button disabled={!progress.completedAt} onClick={() => onNavigate('expansion')}>{progress.completedAt ? 'View kennel expansion' : 'Expansion opens after your first club event'}</button><p>Club results are local to your save. Online leagues and paid expansions are not part of this preview.</p></section>
    {playing && run && liveRound && roundDog && <Suspense fallback={<div className="field-loading-overlay">Preparing the grounds…<button onClick={() => setPlaying(false)}>Return to Field Club</button></div>}>
      {run.exercise === 'training' ? <TrainingGame key={`${run.id}:${run.results.length}`} dog={roundDog} discipline={liveRound.discipline} ability={fieldAbility(roundDog,liveRound.discipline,recordFor(progress,roundDog.id,liveRound.discipline))} onCancel={() => setPlaying(false)} onComplete={finish}/> : liveRound.discipline === 'search' ? <SearchAdventure key={`${run.id}:${run.results.length}`} dog={roundDog} ability={fieldAbility(roundDog,'search',recordFor(progress,roundDog.id,'search'))} seed={run.seed + run.results.length * 97} challenge={run.challenge} onCancel={() => setPlaying(false)} onComplete={finish}/> : liveRound.discipline === 'agility' ? <AgilityGame key={`${run.id}:${run.results.length}`} dog={roundDog} dogName={roundDog.name} agility={fieldAbility(roundDog, 'agility', recordFor(progress, roundDog.id, 'agility'))} mode="training" handlerView onCancel={() => setPlaying(false)} onComplete={(p, report) => finish(report?.score ?? roundScore(p), report)}/> : <FieldGame challenge={run.challenge} key={`${run.id}:${run.results.length}`} dog={roundDog} discipline={liveRound.discipline} ability={fieldAbility(roundDog, liveRound.discipline, recordFor(progress, roundDog.id, liveRound.discipline))} seed={run.seed + run.results.length * 97} onCancel={() => setPlaying(false)} onComplete={finish}/>}
    </Suspense>}
  </div>;
}
