import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const errors = [];
(async()=>{const browser=await chromium.launch();for(const mobile of [false,true]){const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:1100},deviceScaleFactor:1});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:5173/');await page.waitForTimeout(800);await page.evaluate(async()=>{const {useGameStore}=await import('/src/stores/gameStore.ts');const {generateDog}=await import('/src/utils/dogGenerator.ts');const {rescueBreeds}=await import('/src/data/rescueBreeds.ts');const {flushLocalSave}=await import('/src/lib/storage/localDatabase.ts');const state=useGameStore.getState();useGameStore.setState({user:{...state.user,id:'local-player',kennel_name:'Willow Creek Kennel',cash:1250,food_storage:50,last_streak_claim:new Date().toISOString()},dogs:[{...generateDog(rescueBreeds[0],'Scout','local-player',true,'male'),hunger:40,thirst:40,energy_stat:50},generateDog(rescueBreeds[1],'Maple','local-player',true,'female')],hasAdoptedFirstDog:true,tutorialProgress:{completedTutorials:['kennel-basics'],skippedTutorials:[],dismissedHelp:[],showHelpIcons:true}});const {RIBBON_STEPS}=await import('/src/utils/firstRibbon.ts');const live=useGameStore.getState();useGameStore.setState({tutorialProgress:{...live.tutorialProgress,firstRibbon:{dogId:live.dogs[0].id,status:'complete',completed:RIBBON_STEPS.map(s=>s.id),ribbonEarned:true,graduatedAt:new Date(0).toISOString()}}});await flushLocalSave();});await page.reload();await page.getByRole('heading',{name:'Every great kennel starts somewhere.'}).waitFor();await page.waitForTimeout(600);await page.locator('[data-room=dogs]').click();await page.getByText('Scout',{exact:true}).first().click();
await page.getByRole('tab',{name:'Time together',exact:true}).waitFor();
await page.getByRole('button',{name:'Serve a meal',exact:false}).click();
await page.getByText('Fed Scout!',{exact:false}).waitFor();
await page.getByRole('button',{name:'Fresh water',exact:false}).click();
await page.getByRole('button',{name:'Settle down',exact:false}).click();
const beforeCancel = await page.locator('.companion-bond small').textContent();
await page.getByRole('button',{name:'Quiet time',exact:false}).click();
await page.getByRole('button',{name:'Leave quiet time'}).click();
assert.equal(await page.locator('.companion-bond small').textContent(), beforeCancel);
await page.getByRole('button',{name:'Quiet time',exact:false}).click();
const hold=page.getByRole('button',{name:'Hold to offer gentle attention',exact:true});
await hold.focus(); await page.keyboard.down('Space'); await page.waitForTimeout(13000); await page.keyboard.up('Space');
await page.getByRole('button',{name:'Finish your quiet time'}).click();
await page.getByText('Quiet time with Scout:',{exact:false}).waitFor();
if(!await page.getByRole('button',{name:'Quiet time',exact:false}).isDisabled())throw Error('Cooldown missing');
await page.screenshot({path:'.browser.local/companion-'+(mobile?'mobile':'desktop')+'.png'});
await page.getByRole('tab',{name:'Their potential',exact:true}).click();
await page.getByText('A companion with a future',{exact:true}).waitFor();
await page.getByRole('tab',{name:'Time together',exact:true}).click();
await page.getByRole('button',{name:'Choose training',exact:true}).click();
await page.getByRole('button',{name:'Basic Trainer',exact:false}).first().click();
await page.getByText('A step forward for Scout.',{exact:true}).waitFor();
await page.getByRole('button',{name:'Back to your companion',exact:true}).click();
await page.getByRole('tab',{name:'Time together',exact:true}).waitFor();
const overflow=await page.evaluate(()=>document.querySelector('.club-main').scrollWidth>document.querySelector('.club-main').clientWidth+2);
if(overflow)throw Error('Companion view overflows');
await page.reload();
await page.locator('[data-room=dogs]').click();await page.getByText('Scout',{exact:true}).first().click();
await page.getByRole('tab',{name:'Time together',exact:true}).waitFor();
assert.equal(await page.getByRole('button',{name:'Quiet time',exact:false}).isDisabled(), true);
console.log(mobile?'Mobile':'Desktop','care, cancelled bonding, active bonding, cooldown, milestones, training recap and return passed.');
await context.close();}await browser.close(); assert.deepEqual(errors, []);})();
