import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch();
const errors=[];
try { for(const mobile of [false,true]) {
const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:1100}});
const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5173/');await page.waitForTimeout(1200);
await page.evaluate(async()=>{const {useGameStore}=await import('/src/stores/gameStore.ts');const {generateDog}=await import('/src/utils/dogGenerator.ts');const {rescueBreeds}=await import('/src/data/rescueBreeds.ts');const {flushLocalSave}=await import('/src/lib/storage/localDatabase.ts');const state=useGameStore.getState();useGameStore.setState({user:{...state.user,id:'local-player',kennel_name:'Willow Creek Kennel',cash:1250,food_storage:50,last_streak_claim:new Date().toISOString()},dogs:[{...generateDog(rescueBreeds[0],'Scout','local-player',true,'male'),hunger:40,thirst:40,energy_stat:50},generateDog(rescueBreeds[1],'Maple','local-player',true,'female')],hasAdoptedFirstDog:true,tutorialProgress:{completedTutorials:['kennel-basics'],skippedTutorials:[],dismissedHelp:[],showHelpIcons:true}});const {RIBBON_STEPS}=await import('/src/utils/firstRibbon.ts');const live=useGameStore.getState();useGameStore.setState({tutorialProgress:{...live.tutorialProgress,firstRibbon:{dogId:live.dogs[0].id,status:'complete',completed:RIBBON_STEPS.map(s=>s.id),ribbonEarned:true,graduatedAt:new Date(0).toISOString()}}});await flushLocalSave();});await page.reload();await page.getByRole('heading',{name:'Every great kennel starts somewhere.'}).waitFor();await page.waitForTimeout(600);
await page.getByRole('button',{name:'Go to the yard',exact:true}).click();
await page.getByText('Preparing your yard...', {exact:true}).waitFor({state:'hidden'});
await page.waitForTimeout(2000);
await page.screenshot({path:'.browser.local/yard-'+(mobile?'mobile':'desktop')+'.png'});
await page.getByRole('combobox',{name:'Yard companion'}).selectOption({label:'Maple'});
await page.waitForTimeout(1200);
await page.screenshot({path:'.browser.local/yard-athletic-'+(mobile?'mobile':'desktop')+'.png'});
await page.getByRole('combobox',{name:'Yard companion'}).selectOption({label:'Scout'});
await page.waitForTimeout(500);
await page.locator('.yard-stage').scrollIntoViewIfNeeded();
const point=await page.evaluate(async()=>{const {PerspectiveCamera,Vector3}=await import('/node_modules/.vite/deps/three.js');const {YARD_CAMERA}=await import('/src/game/yard/camera.ts');const box=document.querySelector('.yard-stage canvas').getBoundingClientRect();const camera=new PerspectiveCamera(45,box.width/box.height,.1,1000);camera.position.set(...YARD_CAMERA.close.position);camera.lookAt(...YARD_CAMERA.close.target);camera.updateMatrixWorld();const p=new Vector3(3,.06,3).project(camera);return {x:box.x+(p.x+1)*box.width/2,y:box.y+(1-p.y)*box.height/2};});
await page.mouse.click(point.x,point.y);
await page.waitForFunction(()=>Math.abs(Number(document.querySelector('.yard-stage').dataset.ownerX)-3)<.2&&Math.abs(Number(document.querySelector('.yard-stage').dataset.ownerZ)-3)<.2,{},{timeout:20000});
await page.getByRole('button',{name:'Fill water bowl',exact:false}).click();
await page.getByRole('button',{name:'Ask to wait',exact:true}).click();
await page.waitForTimeout(2500);
assert.ok(await page.locator('meter[aria-label=Water]').evaluate(el=>el.value<50));
await page.getByRole('button',{name:'Let them explore',exact:true}).click();
await page.waitForFunction(()=>document.querySelector('meter[aria-label="Water"]')?.value>=99,{},{timeout:20000});
await page.getByRole('button',{name:'Put out a meal',exact:false}).click();
await page.waitForFunction(()=>document.querySelector('meter[aria-label="Food"]')?.value>=99,{},{timeout:20000});
await page.getByRole('button',{name:'Call Scout back',exact:true}).click();
await page.waitForFunction(()=>{const s=document.querySelector('.yard-stage');return Math.hypot(Number(s.dataset.x)-Number(s.dataset.ownerX),Number(s.dataset.z)-Number(s.dataset.ownerZ))<1.2;},{},{timeout:20000});
await page.getByRole('button',{name:'Enter agility training',exact:false}).click();
await page.getByRole('button',{name:'Start session',exact:true}).waitFor();
await page.getByRole('button',{name:'Start session',exact:true}).click();await page.waitForTimeout(3500);
await page.screenshot({path:'.browser.local/yard-course-'+(mobile?'mobile':'desktop')+'.png'});
await page.getByRole('button',{name:'Exit',exact:true}).click();
await page.getByText('A partnership, every day.',{exact:true}).waitFor();
assert.ok(await page.locator('meter[aria-label=Water]').evaluate(el=>el.value>=99));
assert.equal(await page.locator('.kennel-yard').evaluate(el=>el.scrollWidth>el.clientWidth+2),false);
await context.close();
} assert.deepEqual(errors,[]);console.log('Yard desktop/mobile: both rigs, owner direction and recall, food/water, agility entry/exit and layout pass.');
} finally {await browser.close();}
