import FieldClub from '../../game/club/FieldClub';
import { useGameStore } from '../../stores/gameStore';
import { rescueBreeds } from '../../data/rescueBreeds';
import { shopBreeds } from '../../data/shopBreeds';
import { getDogImage } from '../../utils/dogImages';
import { apprenticeshipComplete, nextRibbonStep } from '../../utils/firstRibbon';
import { isAptitudeKnown } from '../../utils/dogDevelopment';
import { getXPForNextBondLevel } from '../../utils/bondSystem';
import FirstRibbonGuide, { type JourneyNavigation } from '../tutorial/FirstRibbonGuide';
import { getKennelCapacity } from '../../utils/kennelCapacity';
import './journey.css';
export default function JourneyHome({onNavigate}:JourneyNavigation) {
 const {dogs,selectedDog,selectDog,tutorialProgress,user,eventRegistrations}=useGameStore();const journey=tutorialProgress.firstRibbon;const graduated=apprenticeshipComplete(tutorialProgress);const dog=dogs.find(d=>d.id===(graduated?selectedDog?.id:journey?.dogId)&&!d.is_dead)??dogs.find(d=>!d.is_dead);
 if(tutorialProgress.fieldClub)return <FieldClub onNavigate={onNavigate}/>;
 if(!dog)return <section className="mission-brief"><h1>A new chapter awaits.</h1><p>Visit your kennel to remember your dogs and choose your next companion.</p><button className="journey-primary" onClick={()=>onNavigate('kennel')}>Open my kennel</button></section>;
 const breed=[...rescueBreeds,...shopBreeds].find(b=>b.id===dog.breed_id);const bondTarget=getXPForNextBondLevel(dog.bond_level);const completed=journey?.completed??[];const finishReady=journey?.status==='active'&&!nextRibbonStep(journey);
 const go=(view:string,activity?:string)=>{selectDog(dog);onNavigate(view,activity?{yardActivity:activity}:undefined);};
 return <div className="journey-home"><header className="journey-title"><div><span className="journey-eyebrow">{graduated?'YOUR STORY CONTINUES':'CHAPTER ONE / A SECOND CHANCE'}</span><h1>{finishReady?'Small beginnings. A first ribbon.':graduated?'A life built together.':'It starts with '+dog.name+'.'}</h1></div><span className="journey-home-tag">{user?.kennel_name||'Your kennel'}</span></header><section className="journey-hero"><div className="journey-dog-portrait"><div className="journey-portrait-halo"/><img src={getDogImage(breed?.name??'Mixed Breed','Sitting')} alt={dog.name}/><div className="journey-dog-name"><span>{dog.is_rescue?'YOUR FOUNDING RESCUE':'YOUR COMPANION'}</span><h2>{dog.name}</h2><p>{breed?.name??'Mixed breed'} · {dog.gender}</p></div>{journey?.ribbonEarned&&<div className="journey-ribbon" aria-label="First ribbon earned">01<span>FIRST RIBBON</span></div>}</div><div className="journey-hero-story">{!graduated?<FirstRibbonGuide onNavigate={onNavigate}/>:<section className="mission-brief"><span className="journey-eyebrow">THE NEXT CHAPTER IS YOURS</span><h2>Care becomes confidence.<br/>Confidence becomes possibility.</h2><p>Keep your partnership growing. Train {dog.name}'s strengths, choose an event you can afford, and save toward a home for your next generation.</p><button className="journey-primary" onClick={()=>go('demo3d')}>Spend time with {dog.name} <span aria-hidden="true">→</span></button><div className="journey-earned"><strong>{eventRegistrations.filter(r=>r.dogId===dog.id&&r.status==='competed').length}</strong><span>Ranked events completed<br/>The welcome ribbon is your beginning.</span></div></section>}</div></section><section className="journey-relationship" aria-label="Your partnership"><div><span className="journey-eyebrow">THE TRUST YOU'RE BUILDING</span><h3>{dog.bond_level===0?'Getting to know you':dog.bond_level<3?'Learning to trust you':'A growing partnership'}</h3><progress aria-label="Bond progress" value={dog.bond_xp} max={bondTarget}/><small>Bond {dog.bond_level} · {dog.bond_xp}/{bondTarget} toward the next level</small></div><div className="journey-needs">{[['Food',dog.hunger],['Water',dog.thirst],['Energy',dog.energy_stat]].map(([name,value])=><div key={name}><strong>{Math.round(Number(value))}%</strong><span>{name}</span><meter aria-label={String(name)} min={0} max={100} value={Number(value)}/></div>)}</div><div className="journey-potential"><span className="journey-eyebrow">POTENTIAL, DISCOVERED TOGETHER</span><h3>{isAptitudeKnown(dog,'agility')?'Agility is coming into focus.':'There is more to discover.'}</h3><p>{isAptitudeKnown(dog,'agility')?`Agility potential ${Math.round(dog.agility)} · ${dog.agility_trained} points developed through training.`:'Bonding and practice reveal strengths that a rescue profile cannot tell you.'}</p></div></section>
 <section className="journey-chapters" aria-label="Your kennel story"><div className="journey-section-heading"><div><span className="journey-eyebrow">FROM ONE RESCUE TO A LASTING KENNEL</span><h2>{graduated?'Choose what you build next.':'The life you are building.'}</h2></div><p>Every chapter grows from the one before it.</p></div><div className="journey-chapter-grid">{[{number:'01',title:'A dog who trusts you',text:'Care, play, and patient training. Your first welcome ribbon marks the beginning.',done:graduated,view:'demo3d',action:'Return to the yard'},{number:'02',title:'A place in the ring',text:'Inspect entry fees and eligibility, compete in the right class, and develop a record over time.',done:eventRegistrations.some(r=>r.status==='competed'),view:'competition',action:'Find our next event'},{number:'03',title:'The next generation',text:`Your kennel holds ${getKennelCapacity(user?.kennel_level??1)} dogs. Breeding needs suitable parents and space for an entire litter, starting at kennel level 3.`,done:dogs.some(d=>d.is_pregnant),view:'breeding',action:'Plan our first litter'}].map(chapter=><article key={chapter.number}><span className="journey-chapter-number">{chapter.number}</span><span className="journey-chapter-status">{chapter.done?'A milestone reached':chapter.number==='01'?'Your chapter now':'Your future kennel'}</span><h3>{chapter.title}</h3><p>{chapter.text}</p>{graduated?<button className="journey-text-button" onClick={()=>go(chapter.view)}>{chapter.action} →</button>:<span className="journey-chapter-note">{chapter.number==='01'?`${Math.min(completed.length,10)} shared moments so far`:'Opens after your first ribbon'}</span>}</article>)}</div></section>{graduated&&<section className="journey-budget"><div><span className="journey-eyebrow">GROW AT A PACE YOU CAN CARE FOR</span><h3>{(user?.kennel_level??1)===1?'Your first expansion: $500':'Your kennel, one thoughtful step at a time'}</h3><p>Keep food and care funded. Earn through suitable work and events before taking on more dogs.</p></div><button className="journey-primary" onClick={()=>go('jobs')}>Find suitable work</button></section>}</div>;
}
