import { useState } from 'react';
import { rescueBreeds } from '../../data/rescueBreeds';
import { getDogImage } from '../../utils/dogImages';
import { STARTING_CASH } from '../../utils/firstRibbon';
import type { Breed } from '../../types';
import '../journey/journey.css';
export default function PoundScene({onDogSelected}:{onDogSelected:(breed:Breed,name:string,gender:'male'|'female')=>void}) {
 const [choices]=useState(()=>[rescueBreeds[0],...rescueBreeds.slice(1).sort(()=>Math.random()-.5).slice(0,2)].map((breed,i)=>({breed,gender:(i===1?'female':'male') as 'male'|'female'})));
 const [selected,setSelected]=useState<number|null>(null);const [name,setName]=useState('');const [adopting,setAdopting]=useState(false);
 return <main className="rescue-opening"><header><span className="journey-eyebrow">PAWS & PEDIGREES / SECOND CHANCE RESCUE</span><h1>Every legacy starts<br/>with one dog.</h1><p>Choose the companion who will start your story. Their potential is still a mystery. What you build together will reveal it.</p></header><div className="rescue-lineup">{choices.map(({breed,gender},i)=><button key={breed.id} className={`rescue-candidate ${selected===i?'selected':''}`} aria-pressed={selected===i} onClick={()=>setSelected(i)}><div className="rescue-portrait"><span>Waiting for a home</span><img src={getDogImage(breed.name,'Sitting')} alt={breed.name}/></div><div className="rescue-candidate-copy"><span>ADULT RESCUE / {gender.toUpperCase()}</span><h2>{breed.name}</h2><p>{breed.description}</p><strong>{selected===i?'Your chosen companion':'Meet this dog'} <span aria-hidden="true">→</span></strong></div></button>)}</div><section className="rescue-adoption"><div><span className="journey-eyebrow">A SMALL BEGINNING</span><h2>A home. A name. A second chance.</h2><p>Your first adoption is free. You start with ${STARTING_CASH} for supplies, a small kennel, and a guided first day together.</p></div><form onSubmit={e=>{e.preventDefault();if(selected===null||!name.trim()||adopting)return;setAdopting(true);const choice=choices[selected];onDogSelected(choice.breed,name.trim(),choice.gender);}}><label htmlFor="rescue-name">What will you call your dog?</label><input id="rescue-name" maxLength={32} value={name} onChange={e=>setName(e.target.value)} placeholder="Their new name" autoComplete="off"/><button className="journey-primary" disabled={selected===null||!name.trim()||adopting}>{adopting?'Preparing your home…':'Bring '+(name.trim()||'your companion')+' home'}</button>{selected===null&&<small>Choose a dog above to begin.</small>}</form></section></main>;
}
