import { useEffect, useState } from 'react';
import { useGameStore } from '../../stores/gameStore';
import { nextRibbonStep, RIBBON_STEPS } from '../../utils/firstRibbon';
import { calculateFoodConsumption } from '../../utils/careCalculations';
import { activityRestriction } from '../../utils/dogDevelopment';
import { bondingRestriction } from '../../utils/companionLoop';
import { flushLocalSave } from '../../lib/storage/localDatabase';
import { isLocalMode } from '../../lib/storage/config';
import './firstRibbon.css';
export interface JourneyNavigation { onNavigate:(view:string,options?:{yardActivity?:string;shopTab?:'items'|'pound'})=>void; compact?:boolean; }
export default function FirstRibbonGuide({onNavigate,compact=false}:JourneyNavigation) {
 const {tutorialProgress,dogs,user,selectDog,startTutorial,acknowledgeRibbonCare}=useGameStore();const journey=tutorialProgress.firstRibbon;const dog=dogs.find(d=>d.id===journey?.dogId&&!d.is_dead);const step=nextRibbonStep(journey);const [message,setMessage]=useState('');const [saving,setSaving]=useState(false);
 useEffect(()=>{if(journey?.status==='active'&&dog&&((user?.food_storage??0)>=calculateFoodConsumption(dog.size)||journey.completed.includes('feed')))useGameStore.getState().recordRibbon(dog.id,'supplies');},[journey,dog,user?.food_storage]);
 if(tutorialProgress.fieldClub)return null;
 if(!journey||journey.status==='complete')return null;
 if(!dog)return <section className="mission-brief"><h2>Your companion needs a new chapter.</h2><button className="journey-primary" onClick={()=>startTutorial('kennel-basics')}>Continue with a living companion</button></section>;
 const go=(view:string,activity?:string)=>{selectDog(dog);onNavigate(view,activity?{yardActivity:activity}:undefined);};
 if(journey.status==='paused')return <section className="mission-brief" aria-label="Your First Ribbon"><span className="journey-eyebrow">YOUR STORY IS WAITING</span><h2>Pick up where you left off.</h2><p>{dog.name}'s progress is kept with your kennel. Finish your first day to open the rest of the game.</p><button className="journey-primary" disabled={saving} onClick={()=>startTutorial('kennel-basics')}>Resume our first day</button><p role="status">{message}</p></section>;
 if(!step)return <section className="mission-brief mission-complete" aria-label="Your First Ribbon"><span className="journey-eyebrow">YOUR FIRST RIBBON</span><h2>You gave them a home.<br/>They gave you a beginning.</h2><p>{dog.name} has finished the welcome meet. You built trust, learned to train together, and earned your first keepsake.</p><button className="journey-primary" onClick={()=>{useGameStore.getState().finishRibbon(dog.id);go('office');}}>Hang our ribbon & choose what's next</button><small>This celebrates participation. Championship titles are earned in ranked events.</small></section>;
 const index=RIBBON_STEPS.findIndex(s=>s.id===step.id);const phase=index<5?'Make yourself at home':index<8?'Build a partnership':'Your first day in the ring';
 const satisfied=step.id==='water'?dog.thirst>=95:step.id==='feed'?dog.hunger>=95:step.id==='rest'?dog.energy_stat>=95:false;
 const recentFetch=step.id==='fetch'&&!!dog.last_fetch&&Date.parse(dog.last_fetch)>Date.now()-15*60000;
 const restriction=['fetch','obedience','agility','meet'].includes(step.id)?activityRestriction(dog):null;
 const cooldown=step.id==='fetch'?bondingRestriction(dog,'fetch'):null;
 const launch=()=>{setMessage('');if(step.id==='supplies'){const before=useGameStore.getState().user?.food_storage??0;useGameStore.getState().purchaseItem(dog.id,{food_storage:10},40,0);const after=useGameStore.getState().user?.food_storage??0;if(after>before)useGameStore.getState().recordRibbon(dog.id,'supplies');else setMessage('You need $40 and room for 10 food units.');return;}if(satisfied){acknowledgeRibbonCare(dog.id,step.id as 'water'|'feed'|'rest');return;}if(recentFetch){acknowledgeRibbonCare(dog.id,'fetch');return;}if(restriction){go('vet');return;}go('demo3d',['yard','move'].includes(step.id)?undefined:step.id);};
 const button=restriction?'Get help with their care':satisfied?'Confirm '+(step.id==='water'?'water is topped up':step.id==='feed'?'your dog is fed':'your dog is rested'):recentFetch?'Continue after your recent fetch':step.id==='water'?'Give fresh water':step.id==='feed'?'Serve their first meal':step.id==='rest'?'Take a breather together':step.id==='fetch'?'Play fetch together':step.id==='obedience'?'Practice our first commands':step.id==='agility'?'Practice the course':step.id==='meet'?'Enter our welcome meet':step.button;
 return <section className={`mission-brief ${compact?'mission-compact':''}`} aria-label="Your First Ribbon" data-tutorial-step={step.id}><div className="mission-heading"><span className="journey-eyebrow">{phase} / {index+1} OF {RIBBON_STEPS.length}</span><progress aria-label="First day progress" max={RIBBON_STEPS.length} value={index}/></div><div className="mission-body"><div><h2>{step.title}</h2><p>{compact?step.how:step.why}</p>{!compact&&<p className="mission-instruction">{step.how}</p>}{restriction&&<p role="status">{restriction}</p>}{step.id==='supplies'&&<small>Balance: ${user?.cash??0} · Pantry: {(user?.food_storage??0).toFixed(1)} units</small>}</div><button className="journey-primary" disabled={!!cooldown&&!recentFetch&&!restriction} onClick={launch}>{button} <span aria-hidden="true">→</span></button></div>{cooldown&&!recentFetch&&!restriction&&<p role="status">{cooldown}</p>}{message&&<p role="status">{message}</p>}<details><summary>Help & progress</summary><p>{step.how}</p><ol>{RIBBON_STEPS.map(s=><li key={s.id}>{journey.completed.includes(s.id)?'Done · ':''}{s.title}</li>)}</ol><p>Cancelled sessions keep your previous progress. Your first food bag costs $40; the welcome meet is free. Independent events, expansion, and breeding open after your first ribbon. Daily rewards begin on a later day.</p><button className="journey-text-button" disabled={saving} onClick={async()=>{setSaving(true);useGameStore.getState().pauseRibbon();try{if(isLocalMode)await flushLocalSave();setMessage('Progress saved.');}catch{setMessage('Could not save. Keep this tab open and try again.');}finally{setSaving(false);}}}>Pause and save</button></details></section>;
}
